# -*- coding: utf-8 -*-
"""DL-LAB2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zR1xWwHHaNz4c5dwkUcke8ou10JyzFWi
"""

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.optimizers import SGD

# Generate some synthetic data for X (features) and y (labels)
# For a binary classification problem, X should have 2 features as specified in Input(shape=(2,))
# y should be binary (0 or 1)
X = np.random.rand(100, 2)  # 100 samples, 2 features
y = (X[:, 0] + X[:, 1] > 1).astype(int).reshape(-1, 1) # A simple classification rule for demonstration, reshaped for model compatibility

model = Sequential([Input(shape=(2,)),
          Dense(16, activation='relu'),
          Dense(16, activation='relu'),
          Dense(1, activation='sigmoid')])
model.compile(loss='binary_crossentropy',optimizer=SGD(learning_rate=0.5), metrics=['accuracy'])

# Batch Gradient Descent → use the whole dataset as one batch
model.fit(X,y,epochs=200,batch_size=len(X),verbose=0)

# Stochastic / mini - batch → small batch size, many updates per epoch
model.fit(X,y,epochs=200,batch_size=16,verbose=0)