# -*- coding: utf-8 -*-
"""DLLAB1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/116w6uCoTr-PrAN23ntVtDKrqnJQm20rX
"""

#Program 1
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

# XOR input and output
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]) # Inputs
y = np.array([[0], [1], [1], [0]]) # Outputs

# Build the MLP model
model = Sequential()
model.add(Dense(8, input_dim=2, activation='relu')) # Hidden layer with 8 neurons
model.add(Dense(1, activation='sigmoid')) # Output layer with 1 neuron for binary output

# Compile the model
model.compile(loss='binary_crossentropy', optimizer=SGD(learning_rate=0.1),
metrics=['accuracy'])

# Train the model
model.fit(X, y, epochs=1000, verbose=0)

# Evaluate the model
_, accuracy = model.evaluate(X, y)

print(f"Model Accuracy: {accuracy * 100:.2f}%")

predictions = model.predict(X)
print("Predictions:")
print(np.round(predictions))

