# -*- coding: utf-8 -*-
"""program1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rPW8j36fdMd-IEiNFyEFl21c_r6k8Zo4
"""


import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

#XOR
X= np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0],[1],[1],[0]])

#build
model=Sequential()
model.add(Dense(8, input_dim=2, activation='relu'))
model.add (Dense (1, activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer=SGD(learning_rate=0.1),
metrics=['accuracy'])

# Train the model
model.fit(X, y, epochs=1000, verbose=0)

# Evaluate the model
_,accuracy = model.evaluate(X, y)

print(f"Model Accuracy:{accuracy * 100:.2f}%")

#make prediction
predictions=model.predict(X)
print("Predictions:")
print(np.round(predictions))